name: Trigger auto deployment for containerapp-maxence

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-maxence-AutoDeployTrigger-f22231bd-96aa-4c56-8519-b233231ec981.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMAXENCE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMAXENCE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMAXENCE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: crmaxence.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPMAXENCE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMAXENCE_REGISTRY_PASSWORD }}
          containerAppName: containerapp-maxence
          resourceGroup: RG-Maxence
          imageToBuild: crmaxence.azurecr.io/containerapp-maxence:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


