name: Trigger auto deployment for containerapp4323

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp4323-AutoDeployTrigger-8b99d250-6b39-43d9-8795-d527d8205a2d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4323_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4323_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4323_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: lschmisser.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4323_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4323_REGISTRY_PASSWORD }}
          containerAppName: containerapp4323
          resourceGroup: RG-lschmisser
          imageToBuild: lschmisser.azurecr.io/containerapp4323:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


